services:
  sgn-rp-connect:
    image: redpandadata/connect:4.106
    container_name: sgn-rp-connect
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - '34196:4195'
    volumes:
      - ../../rpc:/streams:ro
      - ./config:/etc/redpanda-connect
    environment:
      - PG_USER=${POSTGRES__USER}
      - PG_PASSWORD=${POSTGRES__PASSWORD}
      - PG_DATABASE=${POSTGRES__DATABASE}
      - PG_HOST=${POSTGRES__HOST}
      - PG_PORT=${POSTGRES__PORT}
    command: [
      'streams',
      '-w',
      '-o', '/etc/redpanda-connect/connect.yaml',
      '-r', '/etc/redpanda-connect/resources.yaml',
      '/streams'
    ]
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  dwh-net:
    external: true