name: signalfire

services:
  sgn-moex-fetcher:
    build:
      context: ../../../
      dockerfile: services/moex-fetcher/compose/Dockerfile
    container_name: sgn-moex-fetcher
    env_file:
      - path: ../../../.env
        required: true
    restart: unless-stopped
    networks:
      - dwh-net
    volumes:
      - ../config/config.yml:/app/services/moex-fetcher/config/config.yml:ro
      - ../log:/app/services/moex-fetcher/log
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    init: true
    command: ["python", "moex-fetcher.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dwh-net:
    external: true