name: signalfire

include:
  - services/api/compose/docker-compose.yaml
  - services/moex-fetcher/compose/docker-compose.yaml
  - services/rss-fetcher/compose/docker-compose.yaml
  - dwh/compose/redpanda/docker-compose.yaml
  - dwh/compose/dbt/docker-compose.yaml
  - apps/web/compose/docker-compose.yaml

networks:
  dwh-net:
    driver: bridge
    name: dwh-net
