name: signalfire

services:
  sgn-api:
    build:
      context: ../../../
      dockerfile: services/api/compose/Dockerfile
    container_name: sgn-api
    env_file:
      - path: ../../../.env
        required: true
    restart: unless-stopped
    networks:
      - dwh-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "33010:8000"
    volumes:
      - ../log:/app/services/api/log
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    init: true
    command: ["python", "api.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dwh-net:
    external: true
