CREATE DATABASE IF NOT EXISTS stg ON CLUSTER sharded;
CREATE DATABASE IF NOT EXISTS dds ON CLUSTER sharded;
CREATE DATABASE IF NOT EXISTS ods ON CLUSTER sharded;
CREATE DATABASE IF NOT EXISTS dm ON CLUSTER sharded;