moex:
  timezone: "Europe/Moscow"
  lag_start_minutes: 10
  lag_stop_minutes: 20

  # базовое расписание по дням недели
  weekly:
    - week_day: 1
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 2
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 3
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 4
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 5
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 6
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"
    - week_day: 7
      is_work_day: 1
      start_time: "06:20:00"
      stop_time:  "23:59:59"

  special:
    - date: "2026-01-01"
      is_work_day: 0
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-02"
      is_work_day: 0
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-05"
      is_work_day: 1
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-06"
      is_work_day: 1
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-07"
      is_work_day: 0
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-08"
      is_work_day: 1
      start_time: "06:00:00"
      stop_time:  "23:59:59"
    - date: "2026-01-09"
      is_work_day: 1
      start_time: "06:00:00"
      stop_time:  "23:59:59"
