rss_feeds:
  - id: 1
    name: "Interfax"
    link: "https://www.interfax.ru/rss"
    type: "independent"
    location:
      country_code: "ru"
      city: "Moscow"
    language_code: "ru"
    interval: 60

  - id: 2
    name: "RBC"
    link: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss"
    type: "independent"
    location:
      country_code: "ru"
      city: "Moscow"
    language_code: "ru"
    interval: 60

  - id: 3
    name: "Kommersant"
    link: "https://www.kommersant.ru/rss/news.xml"
    type: "independent"
    location:
      country_code: "ru"
      city: "Moscow"
    language_code: "ru"
    interval: 60

  - id: 4
    name: "BBC News"
    link: "https://feeds.bbci.co.uk/news/world/rss.xml"
    type: "independent"
    location:
      country_code: "gb"
      city: "London"
    language_code: "en"
    interval: 60

  - id: 5
    name: "The New York Times"
    link: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
    type: "independent"
    location:
      country_code: "us"
      city: "New York"
    language_code: "en"
    interval: 60

  - id: 6
    name: "Al Jazeera"
    link: "https://www.aljazeera.com/xml/rss/all.xml"
    type: "independent"
    location:
      country_code: "qa"
      city: "Doha"
    language_code: "en"
    interval: 60